#############################################################################
# Makefile for building: LimeSrdCockpit.app/Contents/MacOS/LimeSrdCockpit
# Generated by qmake (3.1) (Qt 6.11.1)
# Project:  LimeSrdCockpit.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile LimeSrdCockpit.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk -mmacosx-version-min=14.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk -mmacosx-version-min=14.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I/usr/local/include -I/opt/local/include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/local/share/qt/mkspecs/macx-clang -F/usr/local/lib
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = LimeSrdCockpit1.0.0
DISTDIR = /Users/taweechai/Documents/pvt/lime-srd-cockpit/.tmp/LimeSrdCockpit1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk -mmacosx-version-min=14.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/usr/local/lib
LIBS          = $(SUBLIBS) -F/usr/local/lib -L/usr/local/lib -L/opt/local/lib -lSoapySDR -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework UniformTypeIdentifiers -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		sdrstreamer.cpp \
		sdrscanner.cpp \
		nmeaparser.cpp \
		headlesstuner.cpp \
		antennatestdialog.cpp moc_mainwindow.cpp \
		moc_sdrstreamer.cpp \
		moc_sdrscanner.cpp \
		moc_headlesstuner.cpp \
		moc_antennatestdialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		sdrstreamer.o \
		sdrscanner.o \
		nmeaparser.o \
		headlesstuner.o \
		antennatestdialog.o \
		moc_mainwindow.o \
		moc_sdrstreamer.o \
		moc_sdrscanner.o \
		moc_headlesstuner.o \
		moc_antennatestdialog.o
DIST          = /usr/local/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/share/qt/mkspecs/features/device_config.prf \
		/usr/local/share/qt/mkspecs/common/unix.conf \
		/usr/local/share/qt/mkspecs/common/mac.conf \
		/usr/local/share/qt/mkspecs/common/macx.conf \
		/usr/local/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/share/qt/mkspecs/common/clang.conf \
		/usr/local/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/share/qt/mkspecs/qconfig.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsstylekit.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsstylekit_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsstylekitimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsstylekitimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssynchronizer.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssynchronizer_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/usr/local/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/share/qt/mkspecs/features/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/share/qt/mkspecs/features/permissions.prf \
		/usr/local/share/qt/mkspecs/features/qt.prf \
		/usr/local/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/share/qt/mkspecs/features/resources.prf \
		/usr/local/share/qt/mkspecs/features/moc.prf \
		/usr/local/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/share/qt/mkspecs/features/uic.prf \
		/usr/local/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/share/qt/mkspecs/features/yacc.prf \
		/usr/local/share/qt/mkspecs/features/lex.prf \
		LimeSrdCockpit.pro mainwindow.h \
		sdrstreamer.h \
		sdrscanner.h \
		nmeaparser.h \
		headlesstuner.h \
		antennatestdialog.h main.cpp \
		mainwindow.cpp \
		sdrstreamer.cpp \
		sdrscanner.cpp \
		nmeaparser.cpp \
		headlesstuner.cpp \
		antennatestdialog.cpp
QMAKE_TARGET  = LimeSrdCockpit
DESTDIR       = 
TARGET        = LimeSrdCockpit.app/Contents/MacOS/LimeSrdCockpit

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 26.2
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/taweechai/Documents/pvt/lime-srd-cockpit/.qmake.stash
EXPORT_VALID_ARCHS = x86_64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/taweechai/Documents/pvt/lime-srd-cockpit/LimeSrdCockpit.pro


include /usr/local/share/qt/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

LimeSrdCockpit.app/Contents/MacOS/LimeSrdCockpit:  $(OBJECTS)  
	@test -d LimeSrdCockpit.app/Contents/MacOS/ || mkdir -p LimeSrdCockpit.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LimeSrdCockpit.pro /usr/local/share/qt/mkspecs/macx-clang/qmake.conf /usr/local/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/share/qt/mkspecs/features/device_config.prf \
		/usr/local/share/qt/mkspecs/common/unix.conf \
		/usr/local/share/qt/mkspecs/common/mac.conf \
		/usr/local/share/qt/mkspecs/common/macx.conf \
		/usr/local/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/share/qt/mkspecs/common/clang.conf \
		/usr/local/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/share/qt/mkspecs/qconfig.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsstylekit.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsstylekit_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsstylekitimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsstylekitimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssynchronizer.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssynchronizer_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/usr/local/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/share/qt/mkspecs/features/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/share/qt/mkspecs/features/permissions.prf \
		/usr/local/share/qt/mkspecs/features/qt.prf \
		/usr/local/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/share/qt/mkspecs/features/resources.prf \
		/usr/local/share/qt/mkspecs/features/moc.prf \
		/usr/local/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/share/qt/mkspecs/features/uic.prf \
		/usr/local/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/share/qt/mkspecs/features/yacc.prf \
		/usr/local/share/qt/mkspecs/features/lex.prf \
		LimeSrdCockpit.pro \
		/usr/local/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile LimeSrdCockpit.pro
/usr/local/share/qt/mkspecs/features/spec_pre.prf:
/usr/local/share/qt/mkspecs/features/device_config.prf:
/usr/local/share/qt/mkspecs/common/unix.conf:
/usr/local/share/qt/mkspecs/common/mac.conf:
/usr/local/share/qt/mkspecs/common/macx.conf:
/usr/local/share/qt/mkspecs/common/sanitize.conf:
/usr/local/share/qt/mkspecs/common/gcc-base.conf:
/usr/local/share/qt/mkspecs/common/gcc-base-mac.conf:
/usr/local/share/qt/mkspecs/common/clang.conf:
/usr/local/share/qt/mkspecs/common/clang-mac.conf:
/usr/local/share/qt/mkspecs/qconfig.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsplatform.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsplatform_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsstylekit.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsstylekit_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsstylekitimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsstylekitimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssynchronizer.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssynchronizer_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlformat_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlls_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmeta.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmeta_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlnetwork.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickeffects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testinternals_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
/usr/local/share/qt/mkspecs/features/qt_functions.prf:
/usr/local/share/qt/mkspecs/features/qt_config.prf:
/usr/local/share/qt/mkspecs/macx-clang/qmake.conf:
/usr/local/share/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/local/share/qt/mkspecs/features/mac/sdk.prf:
/usr/local/share/qt/mkspecs/features/toolchain.prf:
/usr/local/share/qt/mkspecs/features/mac/toolchain.prf:
/usr/local/share/qt/mkspecs/features/default_pre.prf:
/usr/local/share/qt/mkspecs/features/mac/default_pre.prf:
/usr/local/share/qt/mkspecs/features/resolve_config.prf:
/usr/local/share/qt/mkspecs/features/default_post.prf:
/usr/local/share/qt/mkspecs/features/mac/default_post.prf:
/usr/local/share/qt/mkspecs/features/mac/objective_c.prf:
/usr/local/share/qt/mkspecs/features/mac/mac.prf:
/usr/local/share/qt/mkspecs/features/warn_on.prf:
/usr/local/share/qt/mkspecs/features/permissions.prf:
/usr/local/share/qt/mkspecs/features/qt.prf:
/usr/local/share/qt/mkspecs/features/resources_functions.prf:
/usr/local/share/qt/mkspecs/features/resources.prf:
/usr/local/share/qt/mkspecs/features/moc.prf:
/usr/local/share/qt/mkspecs/features/unix/opengl.prf:
/usr/local/share/qt/mkspecs/features/uic.prf:
/usr/local/share/qt/mkspecs/features/unix/thread.prf:
/usr/local/share/qt/mkspecs/features/qmake_use.prf:
/usr/local/share/qt/mkspecs/features/file_copies.prf:
/usr/local/share/qt/mkspecs/features/mac/rez.prf:
/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/share/qt/mkspecs/features/testcase_targets.prf:
/usr/local/share/qt/mkspecs/features/exceptions.prf:
/usr/local/share/qt/mkspecs/features/yacc.prf:
/usr/local/share/qt/mkspecs/features/lex.prf:
LimeSrdCockpit.pro:
/usr/local/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile LimeSrdCockpit.pro

qmake_all: FORCE

LimeSrdCockpit.app/Contents/PkgInfo: 
	@test -d LimeSrdCockpit.app/Contents || mkdir -p LimeSrdCockpit.app/Contents
	@$(DEL_FILE) LimeSrdCockpit.app/Contents/PkgInfo
	@echo "APPL????" > LimeSrdCockpit.app/Contents/PkgInfo
LimeSrdCockpit.app/Contents/Info.plist: 
	@test -d LimeSrdCockpit.app/Contents || mkdir -p LimeSrdCockpit.app/Contents
	@$(DEL_FILE) LimeSrdCockpit.app/Contents/Info.plist
	@set -o pipefail && plutil -convert xml1 -o - /usr/local/share/qt/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.LimeSrdCockpit,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.LimeSrdCockpit,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},14.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,LimeSrdCockpit,g" -e "s,@LIBRARY@,LimeSrdCockpit,g" -e "s,\$${EXECUTABLE_NAME},LimeSrdCockpit,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >LimeSrdCockpit.app/Contents/Info.plist

all: Makefile \
		LimeSrdCockpit.app/Contents/PkgInfo \
		LimeSrdCockpit.app/Contents/Info.plist LimeSrdCockpit.app/Contents/MacOS/LimeSrdCockpit

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/share/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h sdrstreamer.h sdrscanner.h nmeaparser.h headlesstuner.h antennatestdialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp sdrstreamer.cpp sdrscanner.cpp nmeaparser.cpp headlesstuner.cpp antennatestdialog.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r LimeSrdCockpit.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

run: $(TARGET)
	./LimeSrdCockpit.app/Contents/MacOS/LimeSrdCockpit

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/share/qt/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk -mmacosx-version-min=14.0 -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/share/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_sdrstreamer.cpp moc_sdrscanner.cpp moc_headlesstuner.cpp moc_antennatestdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_sdrstreamer.cpp moc_sdrscanner.cpp moc_headlesstuner.cpp moc_antennatestdialog.cpp
moc_mainwindow.cpp: mainwindow.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/lib/QtCore.framework/Headers/QProcess \
		/usr/local/lib/QtCore.framework/Headers/QTimer \
		/usr/local/lib/QtCore.framework/Headers/QFile \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/QProgressBar \
		/usr/local/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/lib/QtWidgets.framework/Headers/QSlider \
		/usr/local/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		sdrstreamer.h \
		/usr/local/lib/QtCore.framework/Headers/QThread \
		/usr/local/lib/QtCore.framework/Headers/QString \
		sdrscanner.h \
		nmeaparser.h \
		/usr/local/lib/QtCore.framework/Headers/QDateTime \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/taweechai/Documents/pvt/lime-srd-cockpit/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/taweechai/Documents/pvt/lime-srd-cockpit -I/usr/local/include -I/opt/local/include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib mainwindow.h -o moc_mainwindow.cpp

moc_sdrstreamer.cpp: sdrstreamer.h \
		/usr/local/lib/QtCore.framework/Headers/QThread \
		/usr/local/lib/QtCore.framework/Headers/QString \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/taweechai/Documents/pvt/lime-srd-cockpit/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/taweechai/Documents/pvt/lime-srd-cockpit -I/usr/local/include -I/opt/local/include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib sdrstreamer.h -o moc_sdrstreamer.cpp

moc_sdrscanner.cpp: sdrscanner.h \
		/usr/local/lib/QtCore.framework/Headers/QThread \
		/usr/local/lib/QtCore.framework/Headers/QString \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/taweechai/Documents/pvt/lime-srd-cockpit/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/taweechai/Documents/pvt/lime-srd-cockpit -I/usr/local/include -I/opt/local/include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib sdrscanner.h -o moc_sdrscanner.cpp

moc_headlesstuner.cpp: headlesstuner.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/QProcess \
		/usr/local/lib/QtCore.framework/Headers/QTimer \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		sdrstreamer.h \
		/usr/local/lib/QtCore.framework/Headers/QThread \
		/usr/local/lib/QtCore.framework/Headers/QString \
		nmeaparser.h \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtCore.framework/Headers/QDateTime \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/taweechai/Documents/pvt/lime-srd-cockpit/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/taweechai/Documents/pvt/lime-srd-cockpit -I/usr/local/include -I/opt/local/include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib headlesstuner.h -o moc_headlesstuner.cpp

moc_antennatestdialog.cpp: antennatestdialog.h \
		/usr/local/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/QProgressBar \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtCore.framework/Headers/QTimer \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		sdrstreamer.h \
		/usr/local/lib/QtCore.framework/Headers/QThread \
		/usr/local/lib/QtCore.framework/Headers/QString \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/taweechai/Documents/pvt/lime-srd-cockpit/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/taweechai/Documents/pvt/lime-srd-cockpit -I/usr/local/include -I/opt/local/include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib antennatestdialog.h -o moc_antennatestdialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtCore.framework/Headers/QTimer \
		mainwindow.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/lib/QtCore.framework/Headers/QProcess \
		/usr/local/lib/QtCore.framework/Headers/QFile \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/QProgressBar \
		/usr/local/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/lib/QtWidgets.framework/Headers/QSlider \
		/usr/local/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		sdrstreamer.h \
		/usr/local/lib/QtCore.framework/Headers/QThread \
		/usr/local/lib/QtCore.framework/Headers/QString \
		sdrscanner.h \
		nmeaparser.h \
		/usr/local/lib/QtCore.framework/Headers/QDateTime \
		headlesstuner.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/QVector
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/lib/QtCore.framework/Headers/QProcess \
		/usr/local/lib/QtCore.framework/Headers/QTimer \
		/usr/local/lib/QtCore.framework/Headers/QFile \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/QProgressBar \
		/usr/local/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/lib/QtWidgets.framework/Headers/QSlider \
		/usr/local/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		sdrstreamer.h \
		/usr/local/lib/QtCore.framework/Headers/QThread \
		/usr/local/lib/QtCore.framework/Headers/QString \
		sdrscanner.h \
		nmeaparser.h \
		/usr/local/lib/QtCore.framework/Headers/QDateTime \
		/usr/local/include/SoapySDR/Device.hpp \
		/usr/local/include/SoapySDR/Config.hpp \
		/usr/local/include/SoapySDR/Config.h \
		/usr/local/include/SoapySDR/Types.hpp \
		/usr/local/include/SoapySDR/Types.h \
		/usr/local/include/SoapySDR/Constants.h \
		/usr/local/include/SoapySDR/Errors.h \
		/usr/local/include/SoapySDR/Formats.hpp \
		/usr/local/include/SoapySDR/Formats.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtGui.framework/Headers/QPaintEvent \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QFormLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/lib/QtWidgets.framework/Headers/QTabWidget \
		/usr/local/lib/QtGui.framework/Headers/QDesktopServices \
		/usr/local/lib/QtCore.framework/Headers/QUrl \
		antennatestdialog.h \
		/usr/local/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		/usr/local/lib/QtCore.framework/Headers/QFileInfo \
		/usr/local/lib/QtCore.framework/Headers/QDir \
		/usr/local/lib/QtCore.framework/Headers/QRegularExpression \
		/usr/local/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/lib/QtGui.framework/Headers/QPalette \
		/usr/local/lib/QtWidgets.framework/Headers/QStyle \
		/usr/local/lib/QtGui.framework/Headers/QPainterPath
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

sdrstreamer.o: sdrstreamer.cpp sdrstreamer.h \
		/usr/local/lib/QtCore.framework/Headers/QThread \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/include/SoapySDR/Device.hpp \
		/usr/local/include/SoapySDR/Config.hpp \
		/usr/local/include/SoapySDR/Config.h \
		/usr/local/include/SoapySDR/Types.hpp \
		/usr/local/include/SoapySDR/Types.h \
		/usr/local/include/SoapySDR/Constants.h \
		/usr/local/include/SoapySDR/Errors.h \
		/usr/local/include/SoapySDR/Formats.hpp \
		/usr/local/include/SoapySDR/Formats.h \
		/usr/local/lib/QtCore.framework/Headers/QFile \
		/usr/local/lib/QtCore.framework/Headers/QFileInfo \
		/usr/local/lib/QtCore.framework/Headers/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sdrstreamer.o sdrstreamer.cpp

sdrscanner.o: sdrscanner.cpp sdrscanner.h \
		/usr/local/lib/QtCore.framework/Headers/QThread \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/include/SoapySDR/Device.hpp \
		/usr/local/include/SoapySDR/Config.hpp \
		/usr/local/include/SoapySDR/Config.h \
		/usr/local/include/SoapySDR/Types.hpp \
		/usr/local/include/SoapySDR/Types.h \
		/usr/local/include/SoapySDR/Constants.h \
		/usr/local/include/SoapySDR/Errors.h \
		/usr/local/include/SoapySDR/Formats.hpp \
		/usr/local/include/SoapySDR/Formats.h \
		/usr/local/lib/QtCore.framework/Headers/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sdrscanner.o sdrscanner.cpp

nmeaparser.o: nmeaparser.cpp nmeaparser.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtCore.framework/Headers/QDateTime \
		/usr/local/lib/QtCore.framework/Headers/QStringList \
		/usr/local/lib/QtCore.framework/Headers/QDate \
		/usr/local/lib/QtCore.framework/Headers/QTime \
		/usr/local/lib/QtCore.framework/Headers/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nmeaparser.o nmeaparser.cpp

headlesstuner.o: headlesstuner.cpp headlesstuner.h \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		/usr/local/lib/QtCore.framework/Headers/QProcess \
		/usr/local/lib/QtCore.framework/Headers/QTimer \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		sdrstreamer.h \
		/usr/local/lib/QtCore.framework/Headers/QThread \
		/usr/local/lib/QtCore.framework/Headers/QString \
		nmeaparser.h \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtCore.framework/Headers/QDateTime \
		/usr/local/lib/QtCore.framework/Headers/QCoreApplication \
		/usr/local/lib/QtCore.framework/Headers/QDebug \
		/usr/local/lib/QtCore.framework/Headers/QFile \
		/usr/local/lib/QtCore.framework/Headers/QDir \
		/usr/local/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/lib/QtCore.framework/Headers/QRegularExpression
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o headlesstuner.o headlesstuner.cpp

antennatestdialog.o: antennatestdialog.cpp antennatestdialog.h \
		/usr/local/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/QProgressBar \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtCore.framework/Headers/QTimer \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		sdrstreamer.h \
		/usr/local/lib/QtCore.framework/Headers/QThread \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/lib/QtCore.framework/Headers/QDir \
		/usr/local/lib/QtCore.framework/Headers/QFile
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o antennatestdialog.o antennatestdialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_sdrstreamer.o: moc_sdrstreamer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sdrstreamer.o moc_sdrstreamer.cpp

moc_sdrscanner.o: moc_sdrscanner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sdrscanner.o moc_sdrscanner.cpp

moc_headlesstuner.o: moc_headlesstuner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_headlesstuner.o moc_headlesstuner.cpp

moc_antennatestdialog.o: moc_antennatestdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_antennatestdialog.o moc_antennatestdialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

